name: underyx
permalink: '/:categories/:year/:month/:day/:title'
timezone: UTC

exclude:
  - vendor/

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: default
  - scope:
      path: ''
      type: posts
    values:
      layout: blog

markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions:
    - smart

analytics_id: UA-46190907-1

gems:
  - jekyll-assets

assets:
  prefix: "/assets"
  sources:
    - "_assets/css"
    - "_assets/js"
    - "_assets/img"
