name: underyx
permalink: '/:categories/:year/:month/:day/:title'
timezone: UTC

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: default
  - scope:
      path: ''
      type: posts
    values:
      layout: blog

sass:
  style: compressed
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions:
    - smart

analytics_id: UA-46190907-1
