professional:
    - name: GitHub
      url: https://github.com/underyx
    - name: LinkedIn
      url: https://linkedin.com/profile/view?id=97624257
    - name: Behance
      url: http://behance.net/underyx

personal:
    - name: Google+
      url: https://plus.google.com/113531113139124157449
    - name: Facebook
      url: https://facebook.com/underyx
    - name: reddit
      url: http://reddit.com/u/underyx
    - name: Twitter
      url: https://twitter.com/underyx
    - name: Pinterest
      url: https://pinterest.com/underyx
    - name: YouTube
      url: https://youtube.com/underyx
    - name: Quora
      url: https://quora.com/Bence-Nagy

fun:
    - name: Steam
      url: https://steamcommunity.com/id/underyx
    - name: last.fm
      url: https://last.fm/user/underyx
    - name: trakt.tv
      url: https://trakt.tv/user/underyx
    - name: Spotify
      url: https://open.spotify.com/user/underyx
    - name: twitch
      url: https://twitch.tv/underyx
    - name: ETF2L
      url: http://etf2l.org/forum/user/24483
