professional:
    - name: GitHub
      url: https://github.com/underyx
    - name: Keybase
      url: https://keybase.io/underyx

personal:
    - name: Twitter
      url: https://twitter.com/underyx
    - name: Hacker News
      url: https://news.ycombinator.com/user?id=underyx
    - name: reddit
      url: https://www.reddit.com/user/underyx
    - name: Facebook
      url: https://www.facebook.com/profile.php?id=1242422521
    - name: YouTube
      url: https://www.youtube.com/user/Underyx
    - name: Google+
      url: https://plus.google.com/+BenceNagy
    - name: Pinterest
      url: https://www.pinterest.com/underyx
    - name: Quora
      url: https://www.quora.com/profile/Bence-Nagy

fun:
    - name: Steam
      url: https://steamcommunity.com/id/underyx
    - name: last.fm
      url: http://www.last.fm/user/underyx
    - name: trakt.tv
      url: https://trakt.tv/users/underyx
    - name: Spotify
      url: https://play.spotify.com/user/underyx
    - name: twitch
      url: http://www.twitch.tv/underyx
